# Generated by Django 2.1.15 on 2020-11-08 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client_list',
            fields=[
                ('NO', models.AutoField(primary_key=True, serialize=False)),
                ('voc_date', models.DateField()),
                ('voc_method', models.CharField(max_length=50)),
                ('client_number', models.IntegerField(max_length=100)),
                ('client_name', models.CharField(max_length=200)),
                ('voc_number', models.IntegerField(max_length=20)),
                ('voc_title', models.TextField()),
                ('voc_content', models.TextField()),
                ('voc_comment', models.TextField()),
                ('voc_manger', models.CharField(max_length=50)),
                ('report', models.CharField(max_length=50)),
                ('partner', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'client_list',
                'managed': False,
            },
        ),
    ]
