# Generated by Django 2.1.15 on 2020-11-08 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientList',
            fields=[
                ('no', models.AutoField(db_column='NO', primary_key=True, serialize=False)),
                ('voc_date', models.DateField(blank=True, null=True)),
                ('voc_method', models.CharField(blank=True, max_length=50, null=True)),
                ('client_number', models.IntegerField(blank=True, null=True)),
                ('client_name', models.CharField(blank=True, max_length=200, null=True)),
                ('voc_number', models.IntegerField(blank=True, null=True)),
                ('voc_title', models.TextField(blank=True, null=True)),
                ('voc_content', models.TextField(blank=True, null=True)),
                ('voc_comment', models.TextField(blank=True, null=True)),
                ('voc_manger', models.CharField(blank=True, max_length=50, null=True)),
                ('report', models.CharField(blank=True, max_length=50, null=True)),
                ('partner', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'client_list',
                'managed': False,
            },
        ),
    ]
